### ISSUE TITLE
Assistant needed :"easy_markers" :

### ISSUE THREAD

**Issue by ZhuJingquan** [marinaKollmitz/human_aware_navigation#2]
Thank you for your share, @marinaKollmitz ,I have git all four packages in workspace ,when using catkin_make to compile these pakages, I couldn't find the "easy_markers" package using google, where can I find the "easy_markers" package, Thank you !
`Could not find a package configuration file provided by "easy_markers" with
  any of the following names:
 easy_markersConfig.cmake
    easy_markers-config.cmake

`

**Comment by ZhuJingquan** [comment]
I have find out "easy_markers"  :https://github.com/DLu/wu_ros_tools/tree/07863d0e95e6684ce187ccdbd182b2f1c405205a

**Comment by marinaKollmitz** [comment]
Glad you figured it out. I will post the link in the readme, thanks for
pointing it out!
Best,

Marina

2017-03-14 8:33 GMT+01:00 ZhuJingquan <notifications@github.com>:

**Comment by ZhuJingquan** [comment]
Thank you again for  sharing  the project, I really learned a lot from your work !
Best,


Jingquan Zhu


------------------ 原始邮件 ------------------
发件人: "Marina Kollmitz";<notifications@github.com>;
发送时间: 2017年3月14日(星期二) 下午4:12
收件人: "marinaKollmitz/human_aware_navigation"<human_aware_navigation@noreply.github.com>; 
抄送: "朱景泉"<857592622@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [marinaKollmitz/human_aware_navigation] Assistant needed:"easy_markers" : (#2)



Glad you figured it out. I will post the link in the readme, thanks for
 pointing it out!
 Best,
 
 Marina
 
 2017-03-14 8:33 GMT+01:00 ZhuJingquan <notifications@github.com>:
