### ISSUE TITLE
Error with dynamic layers plugin

### ISSUE THREAD

**Issue by shrijitsingh99** [marinaKollmitz/human_aware_navigation#3]
Whenever i try to launch the lattice planner i get the follow error
`dynamic_costmap: failed to load dynamic layers plugin: According to the loaded plugin descriptions the class undefined with base class type lattice_planner::DynamicLayers does not exist. Declared types are  dynamic_social_costmap::SocialLayers`

**Comment by marinaKollmitz** [comment]
Hi, did you follow the instructions on the [wiki](https://github.com/marinaKollmitz/human_aware_navigation/wiki)  and did everything compile correctly? Can you give a little more information about which commands you ran and post the output?

**Comment by shrijitsingh99** [comment]
Followed the installation in wiki it compiled successfully.
I had to install the leg_detector package from the original repo as your version didn't compile on Kinetic.
I then added the the lattice planner to my own project.
I basically want to use the lattice planner for my project.
But I can't load the dynamic layers plugin. It keeps giving me this error.

**Comment by marinaKollmitz** [comment]
And you cloned and compiled the human_aware_navigation code as well? Please specify which command you are running (rosrun/roslaunch ... ) and post the complete output.

**Comment by marinaKollmitz** [comment]
To recap: You completed the installation instructions successfully and were able to start the simulation and run the planner in simulation? Your error happens when running the lattice planner on its own?
