### ISSUE TITLE
questions about ‘social_nav_simulation’

### ISSUE THREAD

**Issue by CodeToPoem** [marinaKollmitz/human_aware_navigation#5]
Hi!

I have questions about how to control people to move in Gazebo simulation，which makes it easy to test the planner in the  dynamic situation.

ps:
the people model is set like this in launch files，
 
  <node name="spawn_person1" pkg="gazebo_ros" type="spawn_model" args="-file $(find social_nav_simulation)/gazebo/models/human/walking.sdf -sdf -x 1.9 -y 0.2 -model person1" />

**Comment by marinaKollmitz** [comment]
Hi, 

unfortunately I don't know any good way to control people in the Gazebo simulation. That is why I used the fake people detection node which simulates a detected person walking on a line. For testing I also used to joystick the robot around and recorded the robot poses and afterwards played them back as fake people detections. Like this you can simulate a person walking along some arbitrary path. You can generally try to translate a keyboard or joystick input to simulated people poses, but I did not implement anything like that. Finally, I saw that the v-rep simulator has some build in people simulation where you can make them walk along a path. Maybe that would be interesting for you? 

Best,

Marina

**Comment by CodeToPoem** [comment]
Thanks for advice, and I will learn about the v-rep simulator recently.

And I am using a simulated turtlebot for people simulation in player stage and it works.
