### ISSUE TITLE
people_msgs/PeoplePrediction.h

### ISSUE THREAD

**Issue by ericzzj1989** [marinaKollmitz/human_aware_navigation#6]
Hello, when compiling the code, there comes out this information

human_aware_navigation/people_prediction/include/people_prediction/constant_velocity_prediction.h:42:10: fatal error: people_msgs/PeoplePrediction.h: No such file or directory
 #include <people_msgs/PeoplePrediction.h>

Would you mind providing this message file?

**Comment by marinaKollmitz** [comment]
Hi, did you clone my fork of the people repository: https://github.com/marinaKollmitz/people ? Please confirm that ros can find the correct package by $roscd people_msgs

**Comment by ericzzj1989** [comment]
@marinaKollmitz I have solved this problem as following your wiki https://github.com/marinaKollmitz/human_aware_navigation/wiki. Many thanks for your kind reply.
