### ISSUE TITLE
about  some graphs in experiments

### ISSUE THREAD

**Issue by zkxwy1996** [marinaKollmitz/human_aware_navigation#9]
I want to do some experiments, but I don't know how to draw the following diagram
![1619145013(1)](https://user-images.githubusercontent.com/52746332/115809600-fb7a4300-a41e-11eb-8f47-f678f75e4fbe.png)
Can you teach me how to draw such a picture？Is there any package in ROS？
Thank you very much!

**Comment by marinaKollmitz** [comment]
I used the latex package pgfplots to create the graphs for my paper from data I collected while running the human-aware navigation code. Creating those graphs is not part of this repository.
